Feat(activity-logs): add profile icon to logs
CUSW-chula/cusw-frontend pull request #17
Opened 2024-10-21 17:31 UTC by Romeliette

why detail is always Bold? I try to edit and delete BoldAfterToFrom but it does not change anything

2024-10-22 15:24 UTC, bunnybunbun37204 requested changes
ขึ้นแค่ icon เพราะ activity log กินที่
แล้วทำ hover ด้วยไปดูใน `assigned.tsx` ของกูก็ได้

2024-10-23 08:02 UTC, Romeliette commented
ตรวจด้วยอ้วน

2024-10-23 14:18 UTC, bunnybunbun37204 commented
> why detail is always Bold? I try to edit and delete BoldAfterToFrom but it does not change anything

มึงใช้ `className = semibold`

2024-10-23 14:24 UTC, bunnybunbun37204 commented
ทำ scroll ด้วย

2024-10-23 14:29 UTC, Romeliette commented
> ทำ scroll ด้วย

okok

2024-10-23 17:09 UTC, bunnybunbun37204 approved these changes

2024-10-23 17:09 UTC, merged