feat(activity-logs): pre activity logs kub jubjub
CUSW-chula/cusw-frontend pull request #3
Opened 2024-10-11 11:55 UTC by Romeliette

yang mai finish kub

2024-10-11 14:46 UTC, Romeliette commented
finish leaw kub

2024-10-11 15:02 UTC, bunnybunbun37204 requested changes
แก้ตามนี้งับอ้วง

2024-10-11 15:02 UTC, bunnybunbun37204 commented on src/components/elements/activity-logs.tsx
> +'use client';
หน้านี้ไม่จำเป็นต้อง `use client` โค้ดไม่มีการเรียก browser library ทำ SSR ไปเลยก็ได้

2024-10-13 09:23 UTC, Romeliette commented
commit การแก้ไขไปแล้ว มันขึ้นมั้ย

2024-10-14 15:27 UTC, merged