feat(taskmanager): add filter and sort
CUSW-chula/cusw-frontend pull request #39
Opened 2024-11-12 23:39 UTC by OverIoad

2024-11-12 23:41 UTC, OverIoad commented
There is still a bug in the filtering process. Although the sorting algorithm seems to be working as expected, it hasn't been fully tested yet.

2024-11-16 08:41 UTC, bunnybunbun37204 requested changes
this func didnt work on my pc, or i missed something ?

2024-11-16 08:41 UTC, bunnybunbun37204 commented on src/components/elements/taskmanager.tsx
> +        // Return the task ids array
this func didnt work on my machine

2024-11-16 21:04 UTC, bunnybunbun37204 approved these changes
Approve

2024-11-16 21:04 UTC, merged