feat(component): Add Upload Feature
CUSW-chula/cusw-frontend pull request #7
Opened 2024-10-12 19:16 UTC by bypkt-bk

**Changes Made**
- Added a button to trigger file upload.
- Implemented a hidden input field to handle file selection.
- Created a callback function to process the uploaded file.

**How to Test**
1. Navigate to the component in the application.
2. Click the "Upload" button.
3. Select a file from your device.
4. Confirm that the file upload is processed correctly and logged in the console.

2024-10-12 19:25 UTC, bunnybunbun37204 commented
Merge เข้า dev แทนได้บ่

2024-10-12 19:26 UTC, bypkt-bk commented
ได้คับ

เมื่อ อา. 13 ต.ค. 2024 เวลา 2:25 AM Bunyawat Naunnak <
***@***.***> เขียนว่า:

> PR เข้า dev แทนได้บ่
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CUSW-chula/cusw-frontend/pull/7#issuecomment-2408668170>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWB5SY3RHVGPGRFROAS2PPTZ3FZSXAVCNFSM6AAAAABP2VOICWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBYGY3DQMJXGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-14 15:41 UTC, bunnybunbun37204 requested changes
ดีมาก ไปทำให้เสร็จ เส่วๆๆๆๆ

2024-10-14 15:41 UTC, bunnybunbun37204 commented on src/components/elements/uploadfile.tsx
> +          type="file"
ตัว `FileUploader` ให้เขียนแยก component กันดีกว่าเพื่อการ maintain ง่ายๆ

2024-10-14 15:41 UTC, bunnybunbun37204 commented on src/components/elements/uploadfile.tsx
> +          type="file"
หมายถึงแยกออกจากฟังก์ชัน ไม่ควรยัดอยู่ฟังก์ชันเดียวกน

2024-10-14 15:41 UTC, bunnybunbun37204 commented on src/components/elements/emoji.tsx
อันนี้เสียวมาก พิมพ์หลาย emoji ได้ยังนะ

2024-10-14 15:41 UTC, bunnybunbun37204 commented on src/components/elements/uploadfile.tsx
อันนี้รวมๆดีมาก อยากให้ไปทำ upload ได้หลายไฟล์ แล้วก็ append เข้า list แล้วทำ component แสดงผลไฟล์ที่ upload แล้ว

2024-10-14 15:42 UTC, bunnybunbun37204 commented
conflict ใน นี้กูจัดการให้ทำที่เหลือให้เสร็จพอ ๆ

2024-10-14 15:43 UTC, bypkt-bk commented on src/components/elements/uploadfile.tsx
แปป commit ก่อน

2024-10-14 15:44 UTC, bypkt-bk commented on src/components/elements/emoji.tsx
ต้องหลายอันเหรอกุคิดว่าทำแบบlocketทำอันเดียวพอเปลี่ยนไปเรือยๆ

2024-10-14 15:47 UTC, bypkt-bk commented on src/components/elements/uploadfile.tsx
> +          type="file"
แก้และ

2024-10-16 18:11 UTC, bunnybunbun37204 commented on src/components/elements/workspace.tsx
> +  id: string;
แต่ไม่ต้องแก้ตอนนีี้ก็ได้

2024-10-16 18:29 UTC, bunnybunbun37204 commented
![image](https://github.com/user-attachments/assets/92d292b1-8510-4512-bfb2-1abd360cb586)
มี error อันนี้ด้วย

2024-10-16 18:50 UTC, merged